<?php

return [
    'connections' => [
        'default' => [
            'driver'    => env('DB_DRIVER', 'mysql'),
            'host'      => env('DB_HOST', 'localhost'),
            'database'  => env('DB_DATABASE', ''),
            'username'  => env('DB_USERNAME', ''),
            'password'  => env('DB_PASSWORD', ''),
            'charset'   => env('DB_CHARSET', 'utf8'),
            'collation' => env('DB_COLLATION', 'utf8_unicode_ci'),
            'prefix'    => env('DB_PREFIX', ''),
            'port' => env('DB_PORT', 3306),
            'strict' => true,
        ],
        'bd_alias' => [
            'driver'    => env('DB_BRIDGE_DRIVER', 'mysql'),
            'host'      => env('DB_BRIDGE_HOST', 'localhost'),
            'database'  => env('DB_BRIDGE_DATABASE', ''),
            'username'  => env('DB_BRIDGE_USERNAME', ''),
            'password'  => env('DB_BRIDGE_PASSWORD', ''),
            'charset'   => env('DB_BRIDGE_CHARSET', 'utf8'),
            'collation' => env('DB_BRIDGE_COLLATION', 'utf8_unicode_ci'),
            'prefix'    => env('DB_BRIDGE_PREFIX', ''),
            'port' => env('DB_BRIDGE_PORT', 3306),
        ],
        'bd_translations' => [
            'driver'    => env('DB_TRANSLATION_DRIVER', 'mysql'),
            'host'      => env('DB_TRANSLATION_HOST', 'localhost'),
            'database'  => env('DB_TRANSLATION_DATABASE', ''),
            'username'  => env('DB_TRANSLATION_USERNAME', ''),
            'password'  => env('DB_TRANSLATION_PASSWORD', ''),
            'charset'   => env('DB_TRANSLATION_CHARSET', 'utf8'),
            'collation' => env('DB_TRANSLATION_COLLATION', 'utf8_unicode_ci'),
            'prefix'    => env('DB_TRANSLATION_PREFIX', ''),
            'port' => env('DB_TRANSLATION_PORT', 3306),
        ],
        'bd_route_database' => [
            'driver'    => env('DB_ROUTE_DATABASE_DRIVER', 'mysql'),
            'host'      => env('DB_ROUTE_DATABASE_HOST', 'localhost'),
            'database'  => env('DB_ROUTE_DATABASE_DATABASE', ''),
            'username'  => env('DB_ROUTE_DATABASE_USERNAME', ''),
            'password'  => env('DB_ROUTE_DATABASE_PASSWORD', ''),
            'charset'   => env('DB_ROUTE_DATABASE_CHARSET', 'utf8'),
            'collation' => env('DB_ROUTE_DATABASE_COLLATION', 'utf8_unicode_ci'),
            'prefix'    => env('DB_ROUTE_DATABASE_PREFIX', ''),
            'port' => env('DB_ROUTE_DATABASE_PORT', 3306),
        ],
        'bd_route_database_2' => [
            'driver'    => env('DB_ROUTE_DATABASE_2_DRIVER', 'mysql'),
            'host'      => env('DB_ROUTE_DATABASE_2_HOST', 'localhost'),
            'database'  => env('DB_ROUTE_DATABASE_2_DATABASE', ''),
            'username'  => env('DB_ROUTE_DATABASE_2_USERNAME', ''),
            'password'  => env('DB_ROUTE_DATABASE_2_PASSWORD', ''),
            'charset'   => env('DB_ROUTE_DATABASE_2_CHARSET', 'utf8'),
            'collation' => env('DB_ROUTE_DATABASE_2_COLLATION', 'utf8_unicode_ci'),
            'prefix'    => env('DB_ROUTE_DATABASE_2_PREFIX', ''),
            'port' => env('DB_ROUTE_DATABASE_PORT', 3306),
        ],
        'proxy_logger' => [
            'driver'    => env('DB_PROXY_LOGGER_DRIVER', 'mysql'),
            'host'      => env('DB_PROXY_LOGGER_HOST', 'localhost'),
            'database'  => env('DB_PROXY_LOGGER_DATABASE', ''),
            'username'  => env('DB_PROXY_LOGGER_USERNAME', ''),
            'password'  => env('DB_PROXY_LOGGER_PASSWORD', 'secret'),
            'charset'   => env('DB_PROXY_LOGGER_CHARSET', 'utf8'),
            'collation' => env('DB_PROXY_LOGGER_COLLATION', 'utf8_unicode_ci'),
            'prefix'    => env('DB_PROXY_LOGGER_PREFIX', ''),
            'port' => env('DB_CLIENT_PORT', 3306),
        ],
        
        'proxy_logger2' => [
            'driver'    => env('DB_PROXY_LOGGER2_DRIVER', 'mysql'),
            'host'      => env('DB_PROXY_LOGGER2_HOST', 'localhost'),
            'database'  => env('DB_PROXY_LOGGER2_DATABASE', ''),
            'username'  => env('DB_PROXY_LOGGER2_USERNAME', ''),
            'password'  => env('DB_PROXY_LOGGER2_PASSWORD', 'secret'),
            'charset'   => env('DB_PROXY_LOGGER2_CHARSET', 'utf8'),
            'collation' => env('DB_PROXY_LOGGER2_COLLATION', 'utf8_unicode_ci'),
            'prefix'    => env('DB_PROXY_LOGGER2_PREFIX', ''),
            'port' => env('DB_CLIENT_PORT', 3306),
        ],
        'client_log' => [
            'driver'    => env('DB_CLIENT_DRIVER', 'mysql'),
            'host'      => env('DB_CLIENT_HOST', 'localhost'),
            'database'  => env('DB_CLIENT_DATABASE', ''),
            'username'  => env('DB_CLIENT_USERNAME', ''),
            'password'  => env('DB_CLIENT_PASSWORD', 'secret'),
            'charset'   => env('DB_CLIENT_CHARSET', 'utf8'),
            'collation' => env('DB_CLIENT_COLLATION', 'utf8_unicode_ci'),
            'prefix'    => env('DB_CLIENT_PREFIX', ''),
            'port' => env('DB_CLIENT_PORT', 3306),
        ],
    ]
];